#ifndef MINT_TITLE_SPRITE_H
#define MINT_TITLE_SPRITE_H

#include <gb/gb.h>

#define MINT_TITLE_SPRITE_WIDTH 48u
#define MINT_TITLE_SPRITE_HEIGHT 48u
#define MINT_TITLE_SPRITE_WIDTH_TILES 6u
#define MINT_TITLE_SPRITE_HEIGHT_TILES 6u
#define MINT_TITLE_SPRITE_FRAME_COUNT 1u
#define MINT_TITLE_SPRITE_TILES_PER_FRAME (MINT_TITLE_SPRITE_WIDTH_TILES * MINT_TITLE_SPRITE_HEIGHT_TILES)
#define MINT_TITLE_SPRITE_TILE_COUNT (MINT_TITLE_SPRITE_FRAME_COUNT * MINT_TITLE_SPRITE_TILES_PER_FRAME)

extern const unsigned char mint_title_sprite_tiles[];

void mint_title_sprite_show(UINT8 first_tile, UINT8 first_sprite, UINT8 frame, UINT8 x, UINT8 y);

#endif
